"""
Project State — the single source of truth for the entire pipeline.

Every agent reads from and writes to this state through the LangGraph StateGraph.
The state is persisted to disk as JSON and checkpointed by LangGraph's saver.

Architecture: Deterministic sequential pipeline — each agent runs in a
fixed order with human-in-the-loop approval between scripting and rendering.
"""

from __future__ import annotations

import operator
from enum import Enum
from typing import Annotated, Optional

# ─── Phase Enum ────────────────────────────────────────────────────────────────


class Phase(str, Enum):
    """Pipeline phase — each agent advances the project through these stages."""

    IDLE = "idle"
    INGESTING = "ingesting"
    INDEXED = "indexed"
    PLANNING = "planning"  # Pipeline is determining next step
    SCRIPTING = "scripting"
    SCRIPTED = "scripted"
    AWAITING_APPROVAL = "awaiting_approval"
    APPROVED = "approved"
    SYNTHESIZING = "synthesizing"
    SYNTHESIZED = "synthesized"
    NORMALIZING = "normalizing"
    NORMALIZED = "normalized"
    RENDERING = "rendering"
    RENDERED = "rendered"
    CAPTIONING = "captioning"
    MASTERING = "mastering"
    MASTERED = "mastered"
    EXPORTING = "exporting"
    COMPLETE = "complete"
    ERROR = "error"


# ─── TypedDict State for LangGraph ────────────────────────────────────────────
# LangGraph requires TypedDict (not BaseModel) for its StateGraph schema.
# List fields use operator.add as the reducer → append semantics.

from typing import TypedDict  # noqa: E402


class GraphState(TypedDict, total=False):
    """The single source of truth passed through the LangGraph StateGraph."""

    # ── Core pipeline state ──────────────────────────────────────────────
    phase: Phase
    raw_assets: Annotated[list[dict], operator.add]
    master_index: list[dict]
    user_prompt: str
    paper_edit: Optional[dict]
    approved_edit: Optional[dict]
    synth_assets: Annotated[list[dict], operator.add]
    normalized_clips: dict[str, str]
    render_path: Optional[str]
    render_history: Annotated[list[str], operator.add]  # audit trail of every render_path mutation
    picture_path: Optional[str]  # original render, before audio mastering or captions
    caption_source_path: Optional[str]  # mastered video without burned captions
    editing_mode: str
    audio_provider: str
    sound_effects_enabled: bool
    caption_path: Optional[str]
    caption_style: Optional[dict]  # user-chosen caption style (font, color, position, bg)
    music_path: Optional[str]
    music_prompt: Optional[str]  # hint for Soundstripe music search (includes edit instructions)
    edit_instruction: Optional[str]  # natural-language edit instruction from post-pipeline edits
    overlay_clips: list[dict]  # V2 overlay clips generated by the Scripter (PiP A-roll over B-roll)
    color_grade: Optional[dict]  # colour-grading params (brightness, contrast, saturation, etc.)
    timeline_path: Optional[str]
    errors: Annotated[list[dict], operator.add]
    project_name: str
    created_at: str
    run_id: str  # unique artifact/scratch namespace per execution
    render_settings: Optional[dict]  # optional width/height/CRF override for a re-render

    # ── Editorial QA (Critic agent) ───────────────────────────────────
    critic_feedback: Optional[dict]  # CriticFeedback from the last review
    critic_iteration: int  # number of Scripter→Critic revise cycles so far

    # ── Pipeline orchestration ────────────────────────────────────────
    completed_agents: Annotated[list[str], operator.add]  # Execution history (append-only)
